# -*- coding: utf-8 -*-
"""02_Pandas_Slicing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_EUm9SgGqp8mRzs3-MBeua5F6ECMOb90

# Mission 1

Display the following information [for this dataset](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/u.user).
- The last 5 rows
- The first 5 rows
- The type of each column

Note : start coding something by typing `pd.read...` and explore the different options available, especially the `sep` parameter.
"""

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/u.user", sep="|")

df

"""# Mission 2

Display the first 10 rows [in the following file](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/drinks.csv)

"""

dataframe = pd.read_csv("https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/drinks.csv", sep=",")

dataframe.head(10)

"""Set the "country" column as the index for the dataframe."""

dataframe.set_index('country')

"""# Mission 3

Access the values of the row for **Zimbabwe** (use the index value)  
"""

dataframe.iloc[-1]

"""# Mision 4

Display only the "continent" column value for the country **Zimbabwe**. 
"""

dataframe.iloc[-1, -1]

"""# Mission 5

Rename the columns [of this dataset](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv), try using the following 2 different methods to achieve this:
- Setting column names directly when reading the file 
- Editing after creating the dataframe ([This resource could be useful](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html))
"""

data = pd.read_csv("https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv", index_col= None, header= 0, names=["Ville", "Couleur Reporté", "Forme Reporté", "Etat", "Temps"])

data

data = pd.read_csv("https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv", sep=",")

data.rename(columns={"City": "Ville", "Colors Reported": "Couleur Reporté", "Shape Reported": "Forme Reporté", "State": "Etat", "Time": "Temps"}, inplace=True)
data

"""# Mission 6

Select the first 3 rows and all the columns of the dataframe using iloc
"""

data.iloc[0:3, :]

"""# Mission 7

Achieve the same result as in mission 6 by using loc
"""

data.loc[0:2]